#!/usr/bin/env bun
/**
 * Bench mode 2: cross-language consistency dashboard.
 *
 * For each corpus, runs the same flat set of parameters through all three
 * SDKs — TypeScript in-process, Rust and Go via their `bench` binaries
 * (built from rust/src/bin/bench.rs / go/cmd/bench/main.go) — and reports
 * whether they agree.
 *
 * This is a REPORTING layer, not the actual correctness gate: `cargo test`
 * and `go test ./...` already assert byte-equality against the parity/*.json
 * golden vectors on every commit. This script exists to make that guarantee
 * visible/human-readable and to catch drift introduced by anything the
 * fixed parity vectors don't happen to cover (new corpora, edge cases).
 *
 * Usage: bun bench/run-cross-language.ts
 * Requires `cargo` and `go` on PATH.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Middleware } from "../ts/src/middleware.js";
import type { ChatMessage, LeanpromptConfig } from "../ts/src/types.js";

const REPO_ROOT = join(import.meta.dir, "..");
const CORPORA_DIR = join(import.meta.dir, "corpora");
const RESULTS_DIR = join(import.meta.dir, "results");
const RESULTS_PATH = join(RESULTS_DIR, "cross-language.md");

// Fixed parameter set applied identically to all three languages —
// protect.lastTurns: 0 so the algorithm's effect is visible regardless of
// corpus length (see run-workload.ts's note about the default protecting
// short conversations into a 0%-savings result).
const PARAMS = {
    mode: "on",
    routingKey: "prose",
    routingValue: "extract",
    ratioMillis: 500,
    threshold: 10,
    protectLastTurns: 0,
};

interface LangResult {
    inputTokens: number;
    outputTokens: number;
    method: string;
    messages: unknown;
}

function tsResult(messages: ChatMessage[]): LangResult {
    const config: LeanpromptConfig = {
        mode: PARAMS.mode as LeanpromptConfig["mode"],
        routing: { [PARAMS.routingKey]: PARAMS.routingValue },
        extract: { ratio: PARAMS.ratioMillis / 1000 },
        trigger: { thresholdTokens: PARAMS.threshold },
        protect: { lastTurns: PARAMS.protectLastTurns },
    };
    const [compressed, stats] = new Middleware(config).compressMessages(messages);
    return {
        inputTokens: stats.inputTokens,
        outputTokens: stats.outputTokens,
        method: stats.method,
        messages: compressed,
    };
}

function binArgs(corpusPath: string): string[] {
    return [
        corpusPath,
        "--mode", PARAMS.mode,
        "--routing", `${PARAMS.routingKey}=${PARAMS.routingValue}`,
        "--ratio-millis", String(PARAMS.ratioMillis),
        "--threshold", String(PARAMS.threshold),
        "--protect-last-turns", String(PARAMS.protectLastTurns),
    ];
}

function rustResult(corpusPath: string): LangResult {
    execFileSync("cargo", ["build", "--release", "--bin", "bench"], {
        cwd: join(REPO_ROOT, "rust"),
        stdio: "ignore",
    });
    const bin = join(REPO_ROOT, "rust", "target", "release", "bench");
    const out = execFileSync(bin, binArgs(corpusPath), { encoding: "utf8" });
    return JSON.parse(out);
}

function goResult(corpusPath: string): LangResult {
    const out = execFileSync(
        "go",
        ["run", "./cmd/bench", ...binArgs(corpusPath)],
        { cwd: join(REPO_ROOT, "go"), encoding: "utf8" },
    );
    return JSON.parse(out);
}

/** Order-independent object comparison, order-sensitive for arrays. */
function deepEqual(a: unknown, b: unknown): boolean {
    if (a === b) return true;
    if (typeof a !== typeof b || a === null || b === null) return false;
    if (Array.isArray(a) || Array.isArray(b)) {
        if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return false;
        return a.every((v, i) => deepEqual(v, b[i]));
    }
    if (typeof a === "object" && typeof b === "object") {
        const ak = Object.keys(a as object).sort();
        const bk = Object.keys(b as object).sort();
        if (ak.length !== bk.length || ak.some((k, i) => k !== bk[i])) return false;
        return ak.every((k) => deepEqual((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]));
    }
    return false;
}

mkdirSync(RESULTS_DIR, { recursive: true });

const files = readdirSync(CORPORA_DIR).filter((f) => f.endsWith(".json"));
const lines: string[] = [
    "# Cross-language consistency dashboard",
    "",
    `Generated by \`bun bench/run-cross-language.ts\`. Reports agreement across`,
    "ts/rust/go on the corpora under `bench/corpora/`, at a fixed parameter set",
    "(see PARAMS in the script). This is a reporting layer on top of the real",
    "gate — `cargo test` / `go test ./...` asserting byte-equality against",
    "`parity/*.json` — not a replacement for it.",
    "",
    "| Corpus | ts vs rust | ts vs go | rust vs go | input tok (ts/rust/go) | output tok (ts/rust/go) |",
    "|---|---|---|---|---|---|",
];

let allMatch = true;
for (const file of files) {
    const corpusPath = join(CORPORA_DIR, file);
    const messages: ChatMessage[] = JSON.parse(readFileSync(corpusPath, "utf8"));

    const ts = tsResult(messages);
    const rust = rustResult(corpusPath);
    const go = goResult(corpusPath);

    const tsRust = deepEqual(ts, rust);
    const tsGo = deepEqual(ts, go);
    const rustGo = deepEqual(rust, go);
    allMatch = allMatch && tsRust && tsGo && rustGo;

    const mark = (b: boolean) => (b ? "match" : "**MISMATCH**");
    lines.push(
        `| ${file} | ${mark(tsRust)} | ${mark(tsGo)} | ${mark(rustGo)} | ` +
            `${ts.inputTokens}/${rust.inputTokens}/${go.inputTokens} | ` +
            `${ts.outputTokens}/${rust.outputTokens}/${go.outputTokens} |`,
    );

    console.log(`${file}: ts=${tsRust && tsGo ? "OK" : "MISMATCH"}  (in ${ts.inputTokens} out ${ts.outputTokens}, method ${ts.method})`);
}

lines.push("", allMatch ? "**All corpora agree across all three languages.**" : "**One or more mismatches found — see table above.**");
writeFileSync(RESULTS_PATH, lines.join("\n") + "\n");
console.log(`\nWrote ${RESULTS_PATH}`);

if (!allMatch) {
    process.exit(1);
}
